require 'forwardable'

require 'tundengine/stringifiable_by_class'
require 'tundengine/algebraic_data_type'
require 'tundengine/card_percolator'
require 'tundengine/null_move'
require 'tundengine/move'

require 'tundengine/suits/base'
require 'tundengine/suits/null'
require 'tundengine/suits/oro'
require 'tundengine/suits/copa'
require 'tundengine/suits/espada'
require 'tundengine/suits/basto'

require 'tundengine/ranks/base'
require 'tundengine/ranks/null'
require 'tundengine/ranks/white'
require 'tundengine/ranks/uno'
require 'tundengine/ranks/dos'
require 'tundengine/ranks/tres'
require 'tundengine/ranks/cuatro'
require 'tundengine/ranks/cinco'
require 'tundengine/ranks/seis'
require 'tundengine/ranks/siete'
require 'tundengine/ranks/diez'
require 'tundengine/ranks/once'
require 'tundengine/ranks/doce'

require 'tundengine/cards/card'
require 'tundengine/cards/null'

require 'tundengine/declarations/base'
require 'tundengine/declarations/null'
require 'tundengine/declarations/void'
require 'tundengine/declarations/las_veinte'
require 'tundengine/declarations/las_cuarenta'
require 'tundengine/declarations/tute'

require 'tundengine/tute_values/base'
require 'tundengine/tute_values/nothing'
require 'tundengine/tute_values/capotes'
require 'tundengine/tute_values/victory'

require 'tundengine/deck'

require 'tundengine/stages/base'
require 'tundengine/stages/null'
require 'tundengine/stages/turn'
require 'tundengine/stages/trick'
require 'tundengine/stages/round'
require 'tundengine/stages/match'
require 'tundengine/stages/tournament'

require 'tundengine/player/in_match'
require 'tundengine/player/in_round'
require 'tundengine/player/in_turn'

require 'tundengine/hand'

require 'tundengine/dealer'
require 'tundengine/round_analyzer'

require 'tundengine/strategies/base'
require 'tundengine/strategies/manual'
require 'tundengine/strategies/automatic'
require 'tundengine/strategies/random'